### ISSUE TITLE
How to use GetElements method in proper way to support Linq.

### ISSUE THREAD

**Issue by csvipin31** [ObjectivityLtd/Test.Automation#101]
How do i Write linq on getElment or getElements methods.

I am trying to select an element from a list of item based on the text property.
ex:
lstMainMenu = new ElementLocator(Locator.CssSelector, "#sideMenu >li")
var mainmenu = this.Driver.GetElements(lstMainMenu);
var x= mainmenu.Where(e => e.Text.Contains("HOME"));

then i will do some action.

i am getting below error:

Let me know if i am using this methods in correct ways.

  | Name | Value | Type
-- | -- | -- | --
  | Error | Evaluation of method System.Linq.SystemCore_EnumerableDebugView`1[OpenQA.Selenium.IWebElement].get_Items() calls into native method Microsoft.Win32.SafeNativeMethods.QueryPerformanceCounter(long&). Evaluation of native methods in this context is not supported. |  

thanks
Vipin

**Comment by csvipin31** [comment]
I am trying to do something like below code:

var mainmenu = this.Driver.FindElements(By.CssSelector("#sideMenu >li"));
var selectMainMenu = mainmenu.FirstOrDefault(a => a.Text.Contains("HOME"));
selectMainMenu.Click();

Let me know if its supported, should i just this apporach.

Thanks
Vipin singh

**Comment by raczeja** [comment]
it is working, are you sure that var lstMainMenu contains list of IWebElement ?   
![image](https://user-images.githubusercontent.com/12324498/56121291-184a2900-5f70-11e9-97ed-9cceaa6f34ee.png)

**Comment by csvipin31** [comment]
We can close this, its something to do with quick watch, linq expression works
thanks for help
