### ISSUE TITLE
Selenium Grid Support

### ISSUE THREAD

**Issue by edo248** [ObjectivityLtd/Test.Automation#20]
I started using Test.Automation, but now am thinking of moving to Selenium Grid. It seems this framework does not support it. 

I am thinking of implementing it.  Just want to check first whether it is already planned or under development, not to duplicate effort.

**Comment by raczeja** [comment]
Hi Eduard,
Selenium Grid support is under development, but I cannot give exact deadline where it will be implemented. There is a chance that in this week.

best regards
Jakub

**Comment by raczeja** [comment]
Implemented in version 3.0.3

**Comment by edo248** [comment]
Thank you. Using it already.
