### ISSUE TITLE
Passing Browser Name From CI Tool

### ISSUE THREAD

**Issue by infoneershalin** [ObjectivityLtd/Test.Automation#25]
Hi, Can we have some mechanism here so that we can pass which browser to execute tests against from CI tool or from command line?

**Comment by raczeja** [comment]
Hi,
we are using TeamCity as CI tool and we usually have additional step before test execution to update app.config and set e.g. browser. There are plenty of ways how you can do that e.g. simply text replacement, powershell scripts and xpath,...
best regards
