### ISSUE TITLE
Why DriverContext is not singleton (or inside a singleton)?

### ISSUE THREAD

**Issue by edo248** [ObjectivityLtd/Test.Automation#27]
Hi,

To leave out passing DriverContext throughout the tests I have moved it to a custom singleton. Tests became much clearer for QA Engineers.

Was thinking about the reason It is not implemented as such. I can PR my changes if you're interested.

Eduard

**Comment by raczeja** [comment]
Hi,
Our framework supports parallel execution, so there can be couple of instance of DriverContext created, also each of test can modify DriverContext e.g.
```csharp
        /// <summary>
        /// Before the test.
        /// </summary>
        [SetUp]
        public void BeforeTest()
        {
            this.DriverContext.TestTitle = TestContext.CurrentContext.Test.Name;
            this.LogTest.LogTestStarting(this.driverContext);
        }
```
So we should't use DriverContext in singleton...
Eduard you can show as example of your solution at fork, at least we can look at it

Jakub

**Comment by edo248** [comment]
Hi,

Well anyway DriverContext is created once per ProjectTestBase. What did at this point is modified ProjectTestBase BeforeClass() the following way:

`public class ProjectTestBase : TestBase
    {
        private readonly DriverContext driverContext = new DriverContext();


     /***omitted***/

        [OneTimeSetUp]
        public void BeforeClass()
        {
            this.DriverContext.CurrentDirectory = TestContext.CurrentContext.TestDirectory;
            StartPerformanceMeasure();
            this.DriverContext.Start();

            Browser.Current.Driver = this.DriverContext.Driver;
            Browser.Current.DriverContext = this.DriverContext;

        }


     /***omitted***/

}
`

Where browser is a singleton container for Driver and DriverContext.

`
public class Browser
    {
        public IWebDriver Driver { get; set; }
        public DriverContext DriverContext { get; set; }
        //  private static DriverContext DriverContext { get; set; }
        private static Browser instance = new Browser();

        static Browser() { }

        public static Browser Current
        {
            get
            {
                return instance;
            }
        }

    }
`

The reason I am doing this is to simplify tests and page objects to hide the DriverContext variable. However, I am interested whether this can cause some issue like parallel run, or similar. 

BTW. You did great job with this framework. Really useful.

Eduard

**Comment by raczeja** [comment]
due to possible impact on parallel run I'm closing the issue.
