### ISSUE TITLE
Dynamic Ids

### ISSUE THREAD

**Issue by maharatha** [ObjectivityLtd/Test.Automation#28]
I am really impressed with the Automation framework. It's really amazing.

We use Sencha ExtjS for our web application which generates dynamic ids. Any idea how we can build the test case around it smartly.

**Comment by kf-patrykkulecki** [comment]
I think that you should use other locator types than IDs - css selectors etc

**Comment by raczeja** [comment]
or xpath, here you can find examples how to use css selectors or xpath https://www.simple-talk.com/dotnet/.net-framework/xpath,-css,-dom-and-selenium-the-rosetta-stone/
