### ISSUE TITLE
Performance Measure - need improvements (report on the specific page/action in the log)

### ISSUE THREAD

**Issue by lazovskih** [ObjectivityLtd/Test.Automation#30]
Performance Measure - need improvements (report on the specific page/action in the log)

Hi Team of the Objectivity Ltd.

Thank you for the great framework. There I have improvement request.
As far as I can see the performance measured in the following implementations:
 public class PerformanceHelper.

There is line in the function 'public void StopMeasure':
Logger.Info(CultureInfo.CurrentCulture, "Load Time {0}", this.MeasuredTime);

Which produces line in the Log as:
|Info|Objectivity.Test.Automation.Common.Helpers.PerformanceHelper.StopMeasure|Load Time 1316

Looks like it is would be very helpful if the function will just return the measured value instead of putting it in the log.

There would be easier to report on specific actions (page loads). There is property which is not accessible from the outside:
private long MeasuredTime

Another option to expose the duration is: timer.ElapsedMilliseconds, which is also private.

My implementation would be as the follows (in the PerformanceHelper class):
```
        public double StopMeasureDuration(string title)
        {
            this.timer.Stop();
            var savedTimes = new SavedTimes(title);
            this.MeasuredTime = this.timer.ElapsedMilliseconds;
            savedTimes.SetDuration(this.MeasuredTime);

            this.loadTimeList.Add(savedTimes);

            return this.MeasuredTime;
        }
```

Please let me know if you see this as feasible implementation!
Thank you!

**Comment by raczeja** [comment]
I’m glad that you are using our framework. 
Regarding your suggestion: all measures are stored in list
`
private readonly List<SavedTimes> loadTimeList;
`
I will add getter for that list
`
public List<SavedTimes> GetloadTimeList => this.loadTimeList;
`
so you will be able access to any measure e.g.
`
var subloadTimeList = PerformanceHelper.Instance.GetloadTimeList;
`

**Comment by lazovskih** [comment]
Hi Jakub.
Thank you for the fix.
Unfortunately, this will not make the performance measurements available in the top level classes (test classes and page classes). The list collection will be available only the the compiled WebDriverExtentions class. Ideally (and logically), the measurements should be returned by the method NavigateToAndMeasureTime. In this case the measurments will be available for the test classes and page classes. I know that this can be done in multiple ways. Just feel that this can be improved.

By the way, I was experimenting with the solution and noted that the Scenario property is set to '/' symbol at all times, no matter what passed as the 'title' for StopMeasure method in the NavigateToAndMeasureTime:
```
            PerformanceHelper.Instance.StopMeasure(url.AbsolutePath);
            var subloadTimeList = PerformanceHelper.Instance.GetloadTimeList;
            foreach (var item in subloadTimeList)
            {
                Logger.Info(CultureInfo.CurrentCulture, "Item Duration {0}", item.Duration);
                Logger.Info(CultureInfo.CurrentCulture, "Item Scenario {0}", item.Scenario);
            }
```
This is what I see in the results (Output log):
> |Info|Objectivity.Test.Automation.Common.Extensions.WebDriverExtensions.NavigateToAndMeasureTime|Item Duration 1287
> |Info|Objectivity.Test.Automation.Common.Extensions.WebDriverExtensions.NavigateToAndMeasureTime|Item Scenario /

Thank you again!
Cheers,
Vit

**Comment by raczeja** [comment]
please find example of usage PerformanceHelper in test method:
```
   [Test]
        [TestCaseSource(typeof(TestData), "Credentials")]
        public void FormAuthenticationPageTest(IDictionary<string, string> parameters)
        {
            PerformanceHelper.Instance.StartMeasure();
            new InternetPage(this.DriverContext).OpenHomePage().GoToFormAuthenticationPage();

            var formFormAuthentication = new FormAuthenticationPage(this.DriverContext);
            formFormAuthentication.EnterUserName(parameters["user"]);
            formFormAuthentication.EnterPassword(parameters["password"]);
            PerformanceHelper.Instance.StopMeasure(TestContext.CurrentContext.Test.Name + ".OpenLogOnPage");
            PerformanceHelper.Instance.StartMeasure();
            formFormAuthentication.LogOn();
            PerformanceHelper.Instance.StopMeasure(TestContext.CurrentContext.Test.Name + ".LogInPage");
            Verify.That(
                this.DriverContext,
                () => Assert.AreEqual(parameters["message"], formFormAuthentication.GetMessage));
            var subloadTimeList = PerformanceHelper.Instance.GetloadTimeList;
            foreach (var item in subloadTimeList)
            {
                 Logger.Info(CultureInfo.CurrentCulture, "Item Duration {0}", item.Duration);
                 Logger.Info(CultureInfo.CurrentCulture, "Item Scenario {0}", item.Scenario);
            }
        }
```
This is what I see in the results (Output log):
|Info|TestFramework.ProjectExample.NUnit.Tests.HerokuappTestsNUnit.FormAuthenticationPageTest|Item Duration 10514
|Info|TestFramework.ProjectExample.NUnit.Tests.HerokuappTestsNUnit.FormAuthenticationPageTest|Item Scenario credential_tomsmith_SuperSecretPassword_.OpenLogOnPage
|Info|TestFramework.ProjectExample.NUnit.Tests.HerokuappTestsNUnit.FormAuthenticationPageTest|Item Duration 103
|Info|TestFramework.ProjectExample.NUnit.Tests.HerokuappTestsNUnit.FormAuthenticationPageTest|Item Scenario credential_tomsmith_SuperSecretPassword_.LogInPage
|Info|TestFramework.ProjectExample.NUnit.Tests.HerokuappTestsNUnit.FormAuthenticationPageTest|Item Duration 7769
|Info|TestFramework.ProjectExample.NUnit.Tests.HerokuappTestsNUnit.FormAuthenticationPageTest|Item Scenario credential_wronguser_wrongpassword.OpenLogOnPage
|Info|TestFramework.ProjectExample.NUnit.Tests.HerokuappTestsNUnit.FormAuthenticationPageTest|Item Duration 57
|Info|TestFramework.ProjectExample.NUnit.Tests.HerokuappTestsNUnit.FormAuthenticationPageTest|Item Scenario credential_wronguser_wrongpassword.LogInPage
