### ISSUE TITLE
Objectivity.Test.Automation framework + SpecFlow

### ISSUE THREAD

**Issue by MysteryAchievement** [ObjectivityLtd/Test.Automation#32]
Hello - I have a Specflow based test project that I based on your example using the ProjectTestBase.cs. provided.  When I run the test for my features, I can walk through the code for ProjectTestBase and the DriverContext initializes properly for the driver that I am using but when the BeforeTest method goes out of scope, so does the DriverContext and scenarioContext.

As I debug my version of CommonSteps, the DriverContext is passed in but with a null driver member variable.  ScenarioContext is null too.

What modificationx should I include in my steps classes in order to get them to work with the DriverContext and ScenarioContext from the ProjectTestBase class:?  My step classes, like your CommonSteps class are not derived from any base classes.

Thank you
Chris

**Comment by raczeja** [comment]
Hi,
I just added Test.Automation.ProjectExample.Features [repo ](https://github.com/ObjectivityLtd/Test.Automation.ProjectExample.Features). You can compare that solution with your own.
