### ISSUE TITLE
Cant use Find Element chain

### ISSUE THREAD

**Issue by TheXby** [ObjectivityLtd/Test.Automation#34]
Hello.
someElement.GetElement() throws exception "cant cast "EventFiringWebElement" to "OpenQA.Selenium.IWebDriver".

**Comment by raczeja** [comment]
Hi,
could please provide more details about your issue? the best option will be if you paste you code here...
We are not able to reproduce such problem in our solutions.

**Comment by TheXby** [comment]
Good morning.
Yeah, sure.
locationsList is List<IWebElement>
```
Verify.That(this.DriverContext, () => Assert.IsTrue(locationsList.TrueForAll(location => location
                .GetElement(new ElementLocator(Locator.TagName, "a")).GetAttribute("href")
                .StartsWith("https://goo.gl/maps/")), "Map link should start with 'https://goo.gl/maps/'"));
```

But i have another way to initialize webdriver and i think this is the reason of the problem.
Im using 
`this._driver = new WebdriverEvents(new ChromeDriver(this.ChromeProfile));`

**Comment by admuch** [comment]
Hello, 
please try use separate variable for "EventFiringWebElement" instead of _driver. Please let us know if this will help.

Best regards,
Adrian.

**Comment by TheXby** [comment]
Hello Adrian,
Sorry, but im not sure what you mean
If I remove WebDriverEvents then all working fine
`this._driver = new ChromeDriver(this.ChromeProfile);`

**Comment by TheXby** [comment]
But by this way i loose webdriver events logging

**Comment by raczeja** [comment]
it is implemented in framework https://github.com/ObjectivityLtd/Test.Automation/blob/master/Objectivity.Test.Automation.Common/Logger/MyEventFiringWebDriver.cs, but for some reason we disabled it. W can check it out in free time.
