### ISSUE TITLE
GetElements<Checkbox> threw StaleElementReferenceException

### ISSUE THREAD

**Issue by TheXby** [ObjectivityLtd/Test.Automation#35]
var asd = this.Driver.GetElements<Checkbox>(new ElementLocator(Locator.CssSelector, "#checkboxes input"));
always return the same exception

**Comment by TheXby** [comment]
it works if 
```
foreach (var checkbox in asd )
            {
                checkbox .TickCheckbox();
            }
```

but if i want to get ID of some chekbox
`var elementId = asd.ElementAt(1).GetAttribute("id");`
then i get exception

**Comment by arkadiyala** [comment]
Is framework with SpecFlow working fine? What tools do i need to work on it?

**Comment by AutomateThatOne** [comment]
Very well written framework some excellent ideas, thank you! 👍 

One question, if I wanted to run the Nunit tests or any other tests, in parallel, on different browsers, how can that be achieved getting data from app.config file?

Regards

**Comment by raczeja** [comment]
yes, it's working fine, here you can find instruction https://github.com/ObjectivityLtd/Test.Automation/wiki/Getting-started p.3
