### ISSUE TITLE
Integration with SauceLab

### ISSUE THREAD

**Issue by maharatha** [ObjectivityLtd/Test.Automation#37]
Hi -

I am using your framework and trying to integrate to SauceLab.

 <add key="RemoteWebDriverHub" value="http://username:accesskey@ondemand.saucelabs.com:80/wd/hub" />

Still it throwing up error.

Where should I pass credentials to the Remote Webdriver Hub ?

**Comment by gregpakes** [comment]
I presume this is the same for Browserstack.  The browserstack documentation (https://www.browserstack.com/automate/c-sharp) states that we should specify the **user** and the **key** properties using the **DesiredCapabilities** of the driver.

I cannot see anywhere this is possible?  Am I missing something?

**Comment by admuch** [comment]
Hi,
currently, if you downloaded framework as a nuget package, there is no possibility to set DesiredCapabilities when you choose RemoteDriver. We're working on that and I we expect that will be ready soon. 

Best regards,
Adrian.

**Comment by gregpakes** [comment]
@admuch 

Thanks for the response.  I am happy to help if there is something I can do?  Don't want to submit a PR without discussing design with you first.

Up to you.

**Comment by maharatha** [comment]
Thank You @gregpakes @admuch . Appreciate your responses. Can I expect this feature to be launched sooner as its' holding us up to use SauceLab ?

On a separate note this is one of the best Automation framework I have come across.

**Comment by admuch** [comment]
Hi,
I've added changes to branch 3.0.6 according to adding more capabilities. 
How to use it:
In app.config there is section <DriverCapabilities>. There you can define what kind capabilties you want to add. Example:

  <add key="browserstack.user" value="USERNAME"/>
  <add key="browserstack.key" value="ACCESS_KEY"/>

Please let us know if it works.

Best regards,
Adrian.

**Comment by admuch** [comment]
Example:
`<add key="browserstack.user" value="USERNAME"/>
<add key="browserstack.key" value="ACCESS_KEY"/>`

**Comment by maharatha** [comment]
Thank You Adrian. I will connect and let you know.

**Comment by maharatha** [comment]
Works good, but do not work for Safari browser capabilities with OSx

**Comment by raczeja** [comment]
Safari browser capabilities should be fixed now, @maharatha Could you please test it ?
