### ISSUE TITLE
Identifying best approach to automate 

### ISSUE THREAD

**Issue by arkadiyala** [ObjectivityLtd/Test.Automation#47]
I’m automation tester. I’m trying to identify best test automation approach. My application is developed in C# (DB : SQL Server) and I need to write test automation scripts for UI, DB and REST services. I have below two options available.
-	Selenium + C# 
-	Selenium + Java 
What do I need to consider before going to decide one of the above?
If I go with Selenium + Java, I think I need to have below:  
Maven, Java, IDE(Eclipse), Bamboo or Jenkins(For CI), Bit bucket(For source code), Cucumber, Junit 
If I go with Selenium + C#, what do I need?

Thanks for your help in advance !!

**Comment by lazovskih** [comment]
Hi arkadiyala,
This is not the right place to ask a question like you have asked.
Those guys have already developed framework on C# and it is here for free. You either use it or you don't. The question for you is what you personally prefer: Java or C#.
Try to google it: "selenium java vs c#"

Answer for you question: "If I go with Selenium + C#, what do I need?" - is also personal preference. I use Visual Studio Community + Team Server or GitHub, +NUnit, +MSTest and few other things.
Good luck!
