### ISSUE TITLE
CS50001 Program does not contain a static Main method suitable for an entry point

### ISSUE THREAD

**Issue by arkadiyala** [ObjectivityLtd/Test.Automation#48]
Hi - I have cloned this specflow automation framework. When i click on run button i see below error message . Please help me on it.

Visual studio cannot start debugging because the debug target 'C:\users].......' is missing. Please build the project and retry , or set the outputpath and asseblyname properties appropriately to pint at the correct location for the target assembly 

CS50001 Program does not contain a static Main method suitable for an entry point

**Comment by raczeja** [comment]
Please start with reading https://github.com/ObjectivityLtd/Test.Automation/wiki. 
You can find there:
Run ".nuget\NuGet.exe restore" command in command line in folder with solution file TestFramework.sln

Install “SpecFlow” plugin. Select Tools | Extensions and Updates from the menu in Visual Studio, switch to the Online search on the left and enter “SpecFlow” in the search field at the top right.More details here http://specflow.org/getting-started/

 to run NUnit tests from Visual Studio remember to install NUnit3 Test Adapter
