### ISSUE TITLE
FireFox >47.01

### ISSUE THREAD

**Issue by judeogzewalla** [ObjectivityLtd/Test.Automation#51]
OS: Win 10
FF: Anything > 47.01
Selenium: 3.4
Geckodriver: 0.18.0

I've got a project with ObjectivityNUnit package installed per the getting started section of the wiki. FF 47.01 runs fine, Chrome runs fine. I know in Selenium 3 you need to automate through Geckodriver for FF versions > 47, so I installed most recent Geckodriver binary and added it to my path.

When I execute a test with newer FF (I've tried 32 bit versions of every major and several minor releases between 47 and 54), the browser launches but never navigates. Stepping through it, the test stops in the `OneTimeSetup` at `this.DriverContext.Start()`. error as below:

`Result Message:	OneTimeSetUp: OpenQA.Selenium.WebDriverException : Failed to start up socket within 45000 milliseconds. Attempted to connect to the following addresses: 127.0.0.1:7055`

I honestly feel like I am missing a step, does Geckodriver factor into this at all?

**Comment by raczeja** [comment]
try to set <add key="FirefoxUseLegacyImplementation" value="false"/> in app.config, but with Geckodriver: 0.18.0 you can face another problem https://github.com/mozilla/geckodriver/issues/820, so please use older version geckodriver, in version 3.0.7 of our framework we will move that Maximize Window from DriverContext Start() method to ProjectTestBase class and let users manage it.

**Comment by judeogzewalla** [comment]
Dang- I'm sorry I overlooked that option, navigation works with later FF with that setting fixed. Thanks!
