### ISSUE TITLE
FF not loading add-ons during test runs

### ISSUE THREAD

**Issue by judeogzewalla** [ObjectivityLtd/Test.Automation#52]
Hi,

I've added a reference in app.config to an extension I need to run (uBlock since some internal firewall issues cause 3rd party scripts to take forever to load). I have installed the extension on the default profile, and it's present when I launch FF manually, but from Selenium, FF loads without any add ons.

The reference I made in app.config loads the .xpi in previous versions of FF (e.g. 47.0.1) but doesn't load it in FF 54.0.1.

I also changed the reference to not load the default profile, but when loading a custom profile (which DOES include the add on in FF 54.0.1) test start times were upwards of 1 minute.

Is this a limitation in this recent build of Firefox, or have I (yet again) tried to implement it incorrectly? What should the value reference be for the plugin if the key value is the path?

**Comment by raczeja** [comment]
Hi,
I just updated wiki section https://github.com/ObjectivityLtd/Test.Automation/wiki/Override-browser-profile-preferences,-install-browser-extensions , please let me know if your problem is solved.

**Comment by judeogzewalla** [comment]
That did it - thanks!
