### ISSUE TITLE
Add an Example for Verify Class

### ISSUE THREAD

**Issue by SayantaniRs** [ObjectivityLtd/Test.Automation#55]
Please add an example for Verify Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://objectivityltd.github.io/Test.Automation/html/8097f44b-5724-ad70-5f15-e9571d0dd43e.htm

**Comment by raczeja** [comment]
there are examples for each of Verify Class methods http://objectivityltd.github.io/Test.Automation/html/29fab17c-b453-c161-bf60-cceec6b5192d.htm
```
Verify.That(
    this.DriverContext,
    true,
    false,
    () => Assert.AreEqual(5 + 7 + 2, forgotPassword.EnterEmail(5, 7, 2)),
    () => Assert.AreEqual("Your e-mail's been sent!", forgotPassword.ClickRetrievePassword));
```
and in test examples 
https://github.com/ObjectivityLtd/Test.Automation/blob/master/Objectivity.Test.Automation.Tests.NUnit/Tests/HerokuappTestsNUnit.cs#L72
