### ISSUE TITLE
Option to clean browser/re-instantiate browser between tests?

### ISSUE THREAD

**Issue by judeogzewalla** [ObjectivityLtd/Test.Automation#57]
All my tests run sequentially in  the same instance of a browser, which causes problems if tests need to isolate behavior per session.

I realize spinning up the browser is an expensive operation, but it seems necessary in certain circumstances.  I'd be willing to try to force a delete of cookies between tests, but I can't see where Driver.Manage.DeleteAllCookies() is an option off the DriverContext in the TearDown method.

As always, am I missing something obvious?

**Comment by raczeja** [comment]
you can try this also
```
this.DriverContext.Driver.Manage().Cookies.DeleteAllCookies();
```
