### ISSUE TITLE
Parallel test runs using different browsers

### ISSUE THREAD

**Issue by AutomateThatOne** [ObjectivityLtd/Test.Automation#60]
Very well written framework some excellent ideas, thank you! 👍

One question, if I wanted to run the Nunit tests or any other tests, in parallel, on different browsers, how can that be achieved getting data from app.config file?

Regards

**Comment by raczeja** [comment]
to run test in parallel on different browsers at the same time you have to use Selenium Grid or e.g BrowserStack https://github.com/ObjectivityLtd/Test.Automation/wiki/Selenium-Grid-support and add all browsers to new section group in App.config
```xml
  <environments>
    <Chrome>
      <add key="browser" value="chrome" />
      <add key="os" value="Windows"/>
      <add key="os_version" value="10"/>
      <add key="name" value="parallel_test" />
    </Chrome>
    <Firefox>
      <add key="browser" value="firefox" />
      <add key="os" value="Windows"/>
      <add key="os_version" value="10"/>
      <add key="name" value="parallel_test" />
</Firefox>
```
https://github.com/ObjectivityLtd/Test.Automation/blob/BrowserStackParallelCrossBrowser/Objectivity.Test.Automation.Tests.BrowserStackCrossBrowser/App.config 

You also have to modify ProjectTestBase class
https://github.com/ObjectivityLtd/Test.Automation/blob/BrowserStackParallelCrossBrowser/Objectivity.Test.Automation.Tests.BrowserStackCrossBrowser/ProjectTestBase.cs to read that new section from App.config
```csharp
       public ProjectTestBase(string environment)
        {
            this.environment = environment;
            this.driverContext.CapabilitiesSet += this.DriverContext_CapabilitiesSet;
}
```

I will add more detailed instruction on wiki soon. 

You can also execute tests in parallel on one browser and repeat it for different browsers.  Here https://github.com/ObjectivityLtd/Test.Automation/blob/master/scripts/set_AppConfig_for_tests.ps1 is script for modifying App.config.

**Comment by AutomateThatOne** [comment]
Just back from holidays. 

Thanks alot for this extra information. I will give it a go and see how it runs! 

Thank you very much raczeja :)

**Comment by raczeja** [comment]
please find more detail here https://github.com/ObjectivityLtd/Test.Automation/wiki/Cross-browser-parallel-test-execution-with-BrowserStack%5CSeleniumGrid
