### ISSUE TITLE
Help with Parallelization please

### ISSUE THREAD

**Issue by burakgunay72** [ObjectivityLtd/Test.Automation#67]
Hello everyone, thank you for all your efforts.

I am trying to run the same  Feature file (Login.feature) test steps for Google and IE in parallel, but I am running into some issues. As you can see below, the LoginFeature test class in Login.feature.cs is not getting appended with an NUnit parallelizable atribute  ([NUnit.Framework.ParallelizableAttribute()])

    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Login")]
    public partial class LoginFeature
    {

Changing and saving the App.config is not having any effect on LoginFeature test class even after I click "Yes" to the usual "Do you want to regenerate the feature files now." message.

Here are my setting from App.config

<sectionGroup name="environments">
      <section name="Chrome" type="System.Configuration.NameValueSectionHandler" />
      <section name="InternetExplorer" type="System.Configuration.NameValueSectionHandler" />
    </sectionGroup>
  </configSections>
  <appSettings>
    
    <add key="protocol" value="http" />
    <add key="host" value="the-internet.herokuapp.com" />
    <add key="url" value="" />
    <add key="browser" value="Chrome" /> 
    <add key="browser" value="InternetExplorer" />
........

 <environments>
    <Chrome>
      <add key="browser" value="chrome" />
      <add key="os" value="Windows"/>
      <add key="os_version" value="7"/>
      <add key="name" value="parallel_test" />
    </Chrome>
    <InternetExplorer>
      <add key="browser" value="InternetExplorer" />
      <add key="os" value="Windows"/>
      <add key="os_version" value="7"/>
      <add key="name" value="parallel_test" />
    </InternetExplorer>
  </environments>

I changed the os_version from 10 to 7 since my PC is running on Windows 7.

The app only launches IE, not Chrome. 

Your help will be appreciated.

Thank you.

Burak

**Comment by burakgunay72** [comment]
I attached
[app.txt](https://github.com/ObjectivityLtd/Test.Automation/files/1819489/app.txt)
 the App.config file.

**Comment by raczeja** [comment]
Our framework supports running test in parallel on different browsers at the same time only with [Selenium Grid or e.g BrowserStack ](https://github.com/ObjectivityLtd/Test.Automation/wiki/Selenium-Grid-support), more details [here](https://github.com/ObjectivityLtd/Test.Automation/wiki/Cross-browser-parallel-test-execution-with-BrowserStack-SeleniumGrid/)
