### ISSUE TITLE
Reporting and integrations with TFS for CI

### ISSUE THREAD

**Issue by mjillella** [ObjectivityLtd/Test.Automation#70]
Hi,
can you provide more details on how the reporting would be when we run mutiple test cases? Can we integrate this with TFS and define TFS builds to run the solution?

**Comment by raczeja** [comment]
Hi,
Integration with TFS depends on which unit test framework you use. e.g for  NUnit you can find instruction here  https://stackoverflow.com/questions/40536966/how-to-integrate-nunit-tests-written-in-c-in-tfs-builds?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
