### ISSUE TITLE
Parallel SpecFlow

### ISSUE THREAD

**Issue by mattpickle** [ObjectivityLtd/Test.Automation#76]
https://github.com/ObjectivityLtd/Test.Automation/wiki/Selenium-Parallel-tests-execution

I'm using NUnit with SpecFlow.  Is it possible to run features parallel in Chrome locally?  I don't want to setup Grid or run on Browserstack yet.

**Comment by raczeja** [comment]
It should be possibile, just follow the instruction from https://github.com/techtalk/SpecFlow/wiki/Parallel-Execution
