### ISSUE TITLE
How to start WebDriver (Chrome) in a separate window (console)?

### ISSUE THREAD

**Issue by artkpv** [ObjectivityLtd/Test.Automation#77]
If Selenium tests generated for xunit are run using xunit test runner then output is placed in the console. And Test.Automation runs a WebDriver such that it outputs into the same console, see [this line](https://github.com/ObjectivityLtd/Test.Automation/blob/master/Objectivity.Test.Automation.Common/DriverContext.cs#L525). How to run a WebDriver in a separate window. So that CI process can capture output of it separately? Should it be somehow ChromeDriverService as per [this doc](https://sites.google.com/a/chromium.org/chromedriver/getting-started)?

**Comment by raczeja** [comment]
logs are also saved to file, https://ci.appveyor.com/api/buildjobs/jj493n59w79qdiiv/artifacts/gh-pages_3.1.3.221.zip "TestXunit.log" . It's defined in App.config file 
```xml
<target name="logfile" xsi:type="File" fileName="${basedir}\TestXunit.log" layout="${longdate}|${level}|${callsite}|${message}" />
```
