### ISSUE TITLE
Using JavaScriptClick with EvenFiring turned on getting an error "Unable to cast object of type 'EventFiringWebElement"

### ISSUE THREAD

**Issue by ipinzari** [ObjectivityLtd/Test.Automation#78]
When i try to use MyEventFiringWebDriver i get an error when Using "JavaScriptClick()"

Message = "Unable to cast object of type 'EventFiringWebElement' to type 'OpenQA.Selenium.IWebDriver'."

**Comment by raczeja** [comment]
releted to https://github.com/SeleniumHQ/selenium/issues/5810
issue will be fixed in version 3.1.5
