### ISSUE TITLE
Chrome: Unable to cast object of type 'OpenQA.Selenium.Remote.ReadOnlyDesiredCapabilities' to type 'OpenQA.Selenium.Remote.DesiredCapabilities

### ISSUE THREAD

**Issue by vamsitp** [ObjectivityLtd/Test.Automation#89]
When a test is run on Chrome (Windows/Android) combination (BrowserStack)…

**System.InvalidCastException:**
Unable to cast object of type 'OpenQA.Selenium.Remote.ReadOnlyDesiredCapabilities' to type 'OpenQA.Selenium.Remote.DesiredCapabilities'. 
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
at **[Objectivity.Test.Automation.Common.DriverContext.SetCapabilities()](https://github.com/ObjectivityLtd/Test.Automation/blob/master/Objectivity.Test.Automation.Common/DriverContext.cs#L698)**
at **Objectivity.Test.Automation.Common.DriverContext.Start()**

**Comment by vamsitp** [comment]
ChromeOption's `ToCapabilities()` returns [`capabilities.AsReadOnly()`](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Chrome/ChromeOptions.cs#L589)
For Safari and others there's a comment: [// Should return `capabilities.AsReadOnly()`, and will in a future release.](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Safari/SafariOptions.cs#L149)

**Comment by raczeja** [comment]
could you please confirm that solution from that commit works for you ?

**Comment by vamsitp** [comment]
Sorry, didn't quite get the solution. It was just a config change that adds an <android> node. Was that really the intended fix?

**Comment by raczeja** [comment]
yes, to run test on Android and iPhone with BrowserStack and our framework 3.1.7 you have to add only that config change, please check here https://automate.browserstack.com/builds/3657b5743f48102c6f6481a812cf10062a7d6fa7/sessions/93cce045a748a695d832c27ab2f8b93acc54f6ec test were executed on Android and Iphone

**Comment by vamsitp** [comment]
Hmm...I get a 404/non-found for the above link. I guess the issue is with Chrome (when used with a RemoteWebDriver like BrowserStack) - irrespective of the platform (Android/Windows)…

![image](https://user-images.githubusercontent.com/1181198/48764529-e6d97400-ecd5-11e8-9bf2-7e9e7dbf7d96.png)

**Comment by raczeja** [comment]
try to add this to ProjectTestBase.cs class       
```csharp
	   [BeforeFeature]
        public static void BeforeClass()
        {
		if (BaseConfiguration.TestBrowser == BrowserType.RemoteWebDriver)
                {
                this.DriverContext.CrossBrowserEnvironment = "Android";
	        }
       }
```
and
```xml
   <add key="browser" value="RemoteWebDriver"/>
    <add key="DriverCapabilities" value="CloudProvider"/>
```
https://github.com/ObjectivityLtd/Test.Automation/wiki/Cross-browser-parallel-test-execution-with-SeleniumGrid-or-testing-Cloud-Providers

**Comment by vamsitp** [comment]
OK, shall check and get back
