### ISSUE TITLE
Change of DriverContext.CrossBrowserEnvironment data-type from string to BrowserType causing issues

### ISSUE THREAD

**Issue by vamsitp** [ObjectivityLtd/Test.Automation#92]
**Nuget Version: 3.1.8**

[`DriverContext.CrossBrowserEnvironment`](https://github.com/ObjectivityLtd/Test.Automation/blob/master/Objectivity.Test.Automation.Common/DriverContext.cs#L93)

Prior to **v3.1.8**, since this was a string, we could have something like the following (a Browser-Platform string combo):
```xml
  <appSettings>
    <add key="CrossBrowserEnvironment" value="ChromeWindows" />
  </appSettings>

  <environments>
    <ChromeWindows>
      <add key="browser" value="chrome" />
      <add key="os" value="Windows"/>
      <add key="os_version" value="10"/>
      <add key="resolution" value="1366x768" />
    </ChromeWindows>
    <ChromeMac>
      <add key="browser" value="chrome" />
      <add key="os" value="OS X"/>
      <add key="os_version" value="High Sierra"/>
    </ChromeMac>
    <ChromeAndroid>
      <add key="os_version" value="7.1"/>
      <add key="device" value="Google Pixel" />
      <add key="real_mobile" value="true" />
    </ChromeAndroid>
  </environments>
```
Since it was a generic string, it would populate the `settings` properly:
[`NameValueCollection settings = ConfigurationManager.GetSection("environments/" + this.CrossBrowserEnvironment) as NameValueCollection;`](https://github.com/ObjectivityLtd/Test.Automation/blob/master/Objectivity.Test.Automation.Common/DriverContext.cs#L525)

But with the new change to BrowserType in **v3.1.8**, we no longer have this flexibility in naming the `CrossBrowserEnvironment` to suit our needs...Thoughts?

> NOTE: This is NOT a blocker, as I have a workaround by handling it DriverContext_DriverOptionsSet handler...

**Comment by raczeja** [comment]
We have to replaced using of DesiredCapabilities by browser Options due to changes in Selenium 3.14.0 
https://raw.githubusercontent.com/SeleniumHQ/selenium/master/dotnet/CHANGELOG.

Proper browser Options  are selected by this switch https://github.com/ObjectivityLtd/Test.Automation/blob/master/Objectivity.Test.Automation.Common/DriverContext.cs#L526
Unfortunately in such solution names of environments are tide to BrowserType.

You can edit App.config  to target test on proper OS, this is simple solution with any CI tool
https://github.com/ObjectivityLtd/Test.Automation/wiki/Update-App.config-file-before-test-execution

**Comment by vamsitp** [comment]
Just thinking aloud (haven't really thought about it in detail), but can't we replace [this](https://github.com/ObjectivityLtd/Test.Automation/blob/master/Objectivity.Test.Automation.Common/DriverContext.cs#L525):
```cs
NameValueCollection settings = ConfigurationManager.GetSection("environments/" + this.CrossBrowserEnvironment) as NameValueCollection;
```
with this:
```cs
NameValueCollection settings = ConfigurationManager.GetSection("environments/" + ConfigurationManager.AppSettings["CrossBrowserEnvironment"]) as NameValueCollection;
```
To populate the actual `CrossBrowserEnvironment` property in DriverContext, we can then have custom logic in ProjectTestBase's constructor to parse and populate it to a supported `BrowserType`...

**Comment by raczeja** [comment]
current solution allow us to run the same test with e.g. BrowserStack in parallel on different browsers

I will look at this solution once again in the free time

**Comment by raczeja** [comment]
can you try new solution ? 
nuget package you can download from here
https://ci.appveyor.com/project/ObjectivityAdminsTeam/test-automation/builds/22135896/artifacts
CrossBrowserEnvironment is string again, you have to set it in ProjectTestBase
you also have to set in App.config e.g. <add key="DriverCapabilities" value="Chrome"/> if you are not executing tests in parallel  on different browsers.

**Comment by vamsitp** [comment]
Seems to be working fine...

**Comment by vamsitp** [comment]
Could you publish the package to nuget.org...

Also, as an aside, there seems to be a null-check miss in some of the `SetRemoteDriver*Browser*Options()` methods. The `SetRemoteDriverChromeOptions` has a null-check for `settings` (`if (settings != null)`), while the other methods seem to be missing this check...
Just a thought - maybe instead of having multiple methods with redundant code, we could pass the specific `*Browser*Options` as a `dynamic` parameter so we can have a single method? Something like:

```csharp
private void SetRemoteDriverIEOptions(NameValueCollection driverCapabilitiesConf, NameValueCollection settings, dynamic browserOptions)
{
    // if there are any capability
    if (driverCapabilitiesConf != null)
    {
        // loop through all of them
        for (var i = 0; i < driverCapabilitiesConf.Count; i++)
        {
            string value = driverCapabilitiesConf.GetValues(i)[0];
            Logger.Trace(CultureInfo.CurrentCulture, "Adding driver capability {0}", driverCapabilitiesConf.GetKey(i));
            browserOptions.AddAdditionalCapability(driverCapabilitiesConf.GetKey(i), value, true);
        }
    }

    // if there are any capability
    if (settings != null)
    {
        foreach (string key in settings.AllKeys)
        {
            Logger.Trace(CultureInfo.CurrentCulture, "Adding driver capability {0} from {1}", key, this.CrossBrowserEnvironment);
            browserOptions.AddAdditionalCapability(key, settings[key], true);
        }
    }
}
```

**Comment by vamsitp** [comment]
@raczeja, when can expect the public Nuget?
