### ISSUE TITLE
Mouse Hover is not working while using MS Test in IE browser

### ISSUE THREAD

**Issue by mvaddiboina** [ObjectivityLtd/Test.Automation#94]
Hi I am trying to mouse over to an element in IE browser using this Objectivity MS Test frame work. Mouse hover is not working. Please help me in resolving this issue. I also added the following settings in appconfig.xml

<InternetExplorerPreferences>
  <add key="enablePersistentHover" value="false"/>
 <add key="ignoreZoomSetting" value="true"/>
<add key="ignoreProtectedModeSettings" value="true"/>
  </InternetExplorerPreferences>

**Comment by raczeja** [comment]
it seems to be a ie driver problem: https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver 

> "Hovering Over Elements
> When you attempt to hover over elements, and your physical mouse cursor is within the boundaries of the IE browser window, the hover will not work"
