### ISSUE TITLE
Overriding ChromeDriver issue.

### ISSUE THREAD

**Issue by csvipin31** [ObjectivityLtd/Test.Automation#98]
When i am running Mstest, Chrome driver is lanched and test cases are exectuted.
I created build pipeline in VSTS for the same. I tried to Run the test cases, Chrome driver is not launched, and test cases are failing as this.DriverContext.Start(); thows exception regarding chromedriver path.

So to resolve this i made changes in app.config as suggested in BaseConfiguration. 
I am getting below error. "  (unknown error: DevToolsActivePort file doesn't exist) ".
Provided Path of Local ChromeDriver:

  **<add key="ChromePath" value="C:\Driver\chromedriver.exe"/>**

I also added ChromeArguments in App.config
![image](https://user-images.githubusercontent.com/39784198/55464333-9b9d7d80-5646-11e9-9d49-0a06bfad3dc3.png)

May be i am missing something, couls guys please help.

App.Config changes
<add key="ChromePath" value="C:\Driver\chromedriver.exe"/>
![image](https://user-images.githubusercontent.com/39784198/55464422-d3a4c080-5646-11e9-876c-d5b8fe6954fb.png)

**_Error:_**
OpenQA.Selenium.WebDriverException: 'unknown error: Chrome failed to start: was killed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Driver\chromedriver.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)'

**Comment by raczeja** [comment]
From [Microsoft](https://docs.microsoft.com/pl-pl/azure/devops/pipelines/test/continuous-test-selenium?view=azure-devops): 

> When using the Hosted agent, you should use the Selenium web drivers that are pre-installed on the hosted agents because they are compatible with the browser versions installed on the hosted agent images. The file paths to these drivers can be obtained from the environment variables named IEWebDriver (Internet Explorer), ChromeWebDriver (Google Chrome), and GeckoWebDriver (Firefox). For example,
`driver = new ChromeDriver(Environment.GetEnvironmentVariable("ChromeWebDriver"));`
> 

you can test it with not yet released version of our framework 3.1.11
https://ci.appveyor.com/project/ObjectivityAdminsTeam/test-automation/build/artifacts 
please set a value of  Environment.GetEnvironmentVariable(“ChromeWebDriver”) as 
`<add key="PathToChromeDriverDirectory" value=""/>`

**Comment by csvipin31** [comment]
Thanks for quick reply !!, I will try you suggestion.
When are planning to release new version of the framework.

**Comment by raczeja** [comment]
we can release it when you confirm that it works ....

**Comment by csvipin31** [comment]
Hi Jakub,

i have tested the above branch of the framework 3.1.11, it Works fine. below is the Snap shot of the Run. you could publish the nuget for it.

I provide the valuer of Chrome driver:
 <add key="PathToChromeDriverDirectory" value="C:\Driver"/>

and It worked for me
![image](https://user-images.githubusercontent.com/39784198/55525994-f4205980-56de-11e9-99b4-7e5f8928c71f.png)
thanks for your help !!
Thanks
Vipin Singh
